version: '3.9'

networks:
  deep-network:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.0.0.0/24
          gateway: 10.0.0.254
    internal: true
  middle-network:
    internal: true
  front-network:
  
services:
  mssql:
      container_name: mssql-db
      hostname: mssql-db
      build:
        context: .
        dockerfile: MsSql/Dockerfile          
      ports: 
        - "1433:1433"
      volumes:
        - ./backups:/backups
        - ./data:/var/opt/mssql/data
        - ./log:/var/opt/mssql/log
        - ./secrets:/var/opt/mssql/secrets
      networks:
        deep-network:
          ipv4_address: 10.0.0.2    
        front-network:
  microserv.api:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      MSSQL_IP: 10.0.0.2
    ports:
      - "8080:8080"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    image: ${DOCKER_REGISTRY-}microservapi
    networks:
      - deep-network
      - middle-network
      - front-network
    build:
      context: .
      dockerfile: MicroServ.Api/Dockerfile
      args:
        - MSSQL_IP=10.0.0.2
  